### ISSUE TITLE
Proper rate limit error

### ISSUE THREAD

**Issue by guybedford** [jspm/github#20]
The rate limit response looks like:

```json
{
  "server": "GitHub.com",
  "date": "Wed, 07 Jan 2015 14:55:25 GMT",
  "content-type": "application/json; charset=utf-8",
  "status": "403 Forbidden",
  "x-ratelimit-limit": "60",
  "x-ratelimit-remaining": "0",
  "x-ratelimit-reset": "1420644334",
  "x-github-media-type": "unknown",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "deny",
  "content-security-policy": "default-src 'none'",
  "content-length": "246",
  "access-control-allow-credentials": "true",
  "access-control-expose-headers": "ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
  "access-control-allow-origin": "*",
  "x-github-request-id": "C59B0418:6AE3:7AA50:54AD48DC",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-content-type-options": "nosniff"
}
```

**Comment by EisenbergEffect** [comment]
It would be cool to prompt the user with an option to set up credentials at tis point and retry the install> Something like “Request for package X failed due to a GitHub API rate limit. To fix this issue, configure jspm with your GitHub credentials. Would you like to do this now and retry the install?"

**Comment by guybedford** [comment]
This has been included in https://github.com/jspm/github/commit/f7839615e3ef7f31e7046479c9c264f8ff1fb2a4.

A workflow to immediately correct and resume isn't currently possible with the existing endpoint API, since global configuration changes (saving the new auth) are not currently permitted by endpoints at any time during operation.

This works well as a first implementation though.

**Comment by guybedford** [comment]
To clarify, it looks something like this - 

```
     Updating registry cache...
     Looking up github:twbs/bootstrap
     Downloading github:twbs/bootstrap@3.3.1

err  Error downloading github:twbs/bootstrap

     GitHub rate limit reached. To increase the limit use GitHub authentication.
     Run jspm endpoint config github to set this up.

warn Installation changes not saved.
```

If the user is already authenticated it looks like:

```
     Updating registry cache...
     Looking up github:twbs/bootstrap
     Downloading github:twbs/bootstrap@3.3.1

err  Error downloading github:twbs/bootstrap

     GitHub rate limit reached, with authentication enabled.
     The rate limit will reset in 19 minutes.

warn Installation changes not saved.
```

**Comment by SteveEdson** [comment]
Is it possible to save a authentication token in the config, so that it can be used in CI builds?

My CI stuff is failing occasionally because of Github rate limits.

**Comment by guybedford** [comment]
@SteveEdson there's some docs on this in https://github.com/jspm/jspm-cli/wiki/Endpoints#auto-configuring-endpoints. Allowing a local config file for it is also being tracked as a feature.

**Comment by SteveEdson** [comment]
Sorry if I have misunderstood, but where do I get the `auth_token` from? I'm assuming it is different to a access token?

Is there not a way to run `jspm endpoint config github` with parameters for the username and access token?

Thanks,

Steve

**Comment by guybedford** [comment]
If you read that section, it shows how `jspm endpoint export github` will export the auth token.

TravisCI instructions have also now been included in https://github.com/jspm/jspm-cli/wiki/Endpoints#travis-ci.

**Comment by mryellow** [comment]
On the UX.

```
Would you like to set up your GitHub credentials? [yes]: no
ok   Endpoint github configured successfully.
```

What does this mean?

**Comment by guybedford** [comment]
It means you've set up your GitHub endpoint without credentials or with whatever credentials were already configured.

**Comment by mryellow** [comment]
Yeah seemed like it was telling me it had done something, but still had rate errors after that.

**Comment by kkruit** [comment]
These pages have been moved from "Endpoints" to "Registries" https://github.com/jspm/jspm-cli/wiki/Registries

**Comment by kudos** [comment]
I haven't been able to find evidence of it in the docs or code, but is it possible to configure this from the environment?

**Comment by guybedford** [comment]
@kudos not sure exactly what you mean by configure this from the environment? Have you followed https://github.com/jspm/jspm-cli/wiki/Registries#auto-configuring-registries?

**Comment by kudos** [comment]
It's probably because I was super tired when trying to figure it out, but the first time I read that page I couldn't see how I could apply the same to Circle CI. Mind if I add a section for Circle there?

Also, it could be nice if it passively read that key from the environment instead of needing explicitly passed. Happy to work on a PR for that too if it would be welcome.

**Comment by guybedford** [comment]
@kudos a documentation PR is welcome. Perhaps we should include links to these sections at the top of the page as well so it's easier to find as many seem to miss it.

Supporting an environment variable fallback for the GitHub registry auth token could certainly be an option as well here.

**Comment by trusktr** [comment]
I'm getting

```js
warn Error on download for github:MikeMcl/bignumber.js
     Error: GitHub rate limit reached.

err  Error downloading github:MikeMcl/bignumber.js.
```

which doesn't even show a hint about what to do about it.

@guybedford When will this abomination be fixed? Do you even care about the *very poor* user experience that this causes? Here's [proof of the poor user experience](https://www.google.com/search?q=jspm%20github%20rate%20limit%20reached), right on Google. Is it your goal to have less users than you could have? Do you think everyone wants to create a GitHub account just so they can use a tool like JSPM? No!

It's been over a year since we've been having this problem (yes, it is a problem, not a feature).

I know as well as you do that you don't need to use api.github.com by default, so that we can avoid this problem altogether, and that you can simply just clone a repo or grab releases from the regular HTTP endpoint (f.e. with URLs like "https://github.com/infamous/motor/archive/v0.0.2.zip") instead of fetching release archives through the API (which hardly anyone uses anyways!!!). I know there's no rate limit because I can run `wget` in a while loop and download the release from https://github.com/infamous/motor/archive/v0.0.2.zip over and over and over with no problems. Every once in a blue moon I'll get `ERROR 429: Too Many Requests.`, but at least it won't be blocked like with GitHub API rate limits.

The most disappointing feeling when trying to work on something is when using a tool (like JSPM) that seems really awesome (because it is in many respects), then encountering such a crap error. I'm sorry, but this is a horrible design *bug* that you've made and that you refuse to acknowledge for whatever personal reasons you may have.

I'm sorry if I come off upset, angry, or rude, but it's been over a year since I've been aware of people complaining about this issue, and you just don't care to fix it.

I'm switching any of my projects that use JSPM away from JSPM today, right now, because I don't want to waste any more valuable time with JSPM. JSPM is the only package manager / build system that I've ever wasted *so much time* with, (I'm not exaggerating).

@EisenbergEffect If I were you I'd consider taking `Aurelia` to a different build system for the sake of attracting more users.

**Comment by guybedford** [comment]
@trusktr posting this comment once was more than enough. My response is at https://github.com/aurelia/skeleton-navigation/issues/38#issuecomment-169019572.
