### ISSUE TITLE
git location service (using git+ssh instead of https download)

### ISSUE THREAD

**Issue by benib** [jspm/github#34]
Hi

I'd be interested in a Location Service that uses git+ssh instead of https downloads.
This would allow for authentication using a running ssh-agent which I prefer over storing credentials or generating tokens for all packages.
Additionally this would make it possible to install packages from any git repository and not just Github.

As far as I get it, one idea behind using https is to be able to load this directly from the browser, which for git+ssh doesn't work. I'm I mistaken here?

I'm willing to put some work into this, but wanted to ask for other opinions first. Do you think this would be useful? Should it be another Location Service or somehow merged/integrated with this github one?

**Comment by guybedford** [comment]
Certainly you can look at using jspm-git for this - https://github.com/jspm/jspm-cli/wiki/Community-Projects#endpoints.

The features provided through the API interface to GitHub are:
* Repo redirects - often repos move, and it will handle this redirection for you
* Installing from release archives - eg when installing Bootstrap we use the zip file instead of cloning the repo.

If you don't need the above, you can easily configure jspm-git to work with GitHub as an alternative `github` endpoint.

**Comment by benib** [comment]
Ah nice. It already exists. Missed that. Thanks for the pointers.
